# permissions for end users to edit examplecrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: examplecrd-editor-role
rules:
- apiGroups:
  - rana.example.com
  resources:
  - examplecrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rana.example.com
  resources:
  - examplecrds/status
  verbs:
  - get
